  """ General Usability features
set modeline
set tags=tags;

  """ Shortcuts
nnoremap <C-Down> <C-W><C-J>
nnoremap <C-Up> <C-W><C-K>
nnoremap <C-Right> <C-W><C-L>
nnoremap <C-Left> <C-W><C-H>

  """ Tab Configuration
filetype plugin indent off
set tabstop=2
set expandtab

""" Remove trailing whitespace in the entire document                                                                                                                                                                                         
command Noblank :%s/[ \t]*$//g | :nohl                                                                                                                                                                                                        
map [[ :Noblank<CR> 

  """ Calculate Statusline and show it.
let gitBranch = system("git branch | egrep '^*' | tr -d '\n' | tr -d '*' | tr -d ' '")

  """ Add filename
let statusLineText = "(File: ". expand("%:t") .")"

  """ Add branch spec (if any)
if strlen(gitBranch)

  let statusLineText .= "(br:". gitBranch .") "

else

  let statusLineText .= "(gitless) "

endif

set laststatus=2
set statusline=%y%{statusLineText}

  """ Template Configuration
autocmd BufNewFile *.php 0r ~/.vim/templates/php
autocmd BufNewFile *.py 0r ~/.vim/templates/python
autocmd BufNewFile *.html 0r ~/.vim/templates/html
autocmd BufNewFile *.htm 0r ~/.vim/templates/html
autocmd BufNewFile *.js 0r ~/.vim/templates/javascript
