#!/usr/bin/python

import json, httplib, urllib, sys

params  = urllib.urlencode({});
headers = {'PRIVATE-TOKEN': 'JCJjESaVgKsa9zmS'};

conn = httplib.HTTPSConnection("vlpab..net:443");
conn.request("GET", "/api/v3/projects", params, headers);

responseObject = conn.getresponse();

if responseObject.status != 200:
  print("Error Enumerating Projects: %d" % responseObject.status);
  sys.exit(1)

jsonResponse = json.loads( responseObject.read() )

for project in jsonResponse:
  print ("---")
  print ("ID: "+   str(project['id']))
  print ("Name: "+ project['name'])
  print ("URL: "+  project['web_url'])

